### ISSUE TITLE
terminated with exception undefined method `chomp' for nil:NilClass

### ISSUE THREAD

**Issue by jlcrow** [crazy-max/docker-svn2git-mirror#3]
[twhybris] 
[twhybris] ## Info about SVN repository...
[twhybris] Path: twm_code_base
[twhybris] URL: https://svn.totalwine.com/svn/twm_code_base
[twhybris] Relative URL: ^/
[twhybris] Repository Root: https://svn.totalwine.com/svn/twm_code_base
[twhybris] Repository UUID: d56a3af8-c092-443f-9987-f536df04eac3
[twhybris] Revision: 50775
[twhybris] Node Kind: directory
[twhybris] Last Changed Author: sn-rNagaraju
[twhybris] Last Changed Rev: 50775
[twhybris] Last Changed Date: 2019-03-11 04:38:54 -0400 (Mon, 11 Mar 2019)
[twhybris] 
[twhybris] 
[twhybris] ## Init Git repository...
[twhybris] #<Thread:0x00005612e9581748@/usr/lib/ruby/gems/2.5.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:404 run> terminated with exception (report_on_exception is true):
[twhybris] /usr/lib/ruby/gems/2.5.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:405:in `block (2 levels) in run_command': undefined method `chomp' for nil:NilClass (NoMethodError)
[twhybris] 	from /usr/lib/ruby/gems/2.5.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:405:in `loop'
[twhybris] 	from /usr/lib/ruby/gems/2.5.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:405:in `block in run_command'
[twhybris] Initialized empty Git repository in /data/twhybris/repo/.git/
[twhybris] command failed:

**Comment by crazy-max** [comment]
@jlcrow  Can you post your config file pls ?

**Comment by crazy-max** [comment]
Ok got it, it's an upstream issue from https://github.com/nirvdrum/svn2git.

**Comment by captain-proton** [comment]
Hi,

seems like this issue can be opened again, due to the changes in commit 22f47ce206fe3782163aa15508b1725b193a53e1. For each configured repo a git rebase script is created through the entrypoint.sh.

https://github.com/crazy-max/docker-svn2git-mirror/blob/9fa76572c9cce828d4fcbdd7a808a2fc28650b91/entrypoint.sh#L124

In my case each call to `svn2git` inside the script causes the error. Inside the ruby script `migration.rb` the stdin gets loaded.

```ruby
# We need to fetch input from the user to pass through to the underlying sub-process.  We'll constantly listen
# for input and place any received values on a queue for consumption by a pass-through thread that will forward
# the contents to the underlying sub-process's stdin pipe.
@stdin_thread ||= Thread.new do
    loop { @stdin_queue << $stdin.gets.chomp }
end
```

As shown in the log stated by @jlcrow `$stdin.gets.chomp` causes the error. Don't know the differences between Alpine 3.7 and 3.9/10, but 3.7 works for me.
